MenApparel/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('apparels/', include('apparelapp.urls')),
    path('', RedirectView.as_view(url='apparels/')),
    path('accounts/', include('django.contrib.auth.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apparelapp/urls.py
from django.urls import path
from .views import (HomeView, ApparelsView,
                    TopwearListView, BottomwearListView, FootwearListView,
                    ApparelDetailView, CartListView, CartDeleteView, CartUpdateView,
                    ContactFormView, UserInfoDetailView, CreateUser, OrderHistoryListView,
                    thankyoupage, redirecthome)

app_name = 'apparelapp'

urlpatterns = [
    path('', redirecthome, name='redirecthome'),
    path('home/', HomeView.as_view(), name='home'),

    path('catalog/', ApparelsView.as_view(), name='apparels'),
    path('catalog/topwears', TopwearListView.as_view(), name='topapparels'),
    path('catalog/bottomwears', BottomwearListView.as_view(), name='botapparels'),
    path('catalog/footwears', FootwearListView.as_view(), name='footapparels'),

    path('Addcart/<int:pk>/', ApparelDetailView.as_view(), name='addcart'),
    path('delete/<int:pk>/', CartDeleteView.as_view(), name='delete'),
    path('update/<int:pk>/', CartUpdateView.as_view(), name='update'),
    path('cart/', CartListView.as_view(), name='cart'),

    path('/history', OrderHistoryListView.as_view(), name='history'),
    # path(),

    path('account/', UserInfoDetailView.as_view(), name='account'),
    path('register/', CreateUser.as_view(), name='register'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('thankyou/', thankyoupage, name='thankyou')
]

apparelapp/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.db import connection
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User

# from django.db.models import Q

class Apparel(models.Model):
    TYPE_CHOICES = (
        ('Topwear', 'Topwear'),
        ('Bottomwear', 'Bottomwear'),
        ('Footwear', 'Footwear')
    )

    SUBTYPE_CHOICES = (
        ('Shoes', 'Shoes'),
        ('Shirts', 'Shirts'),
        ('Shorts', 'Shorts'),
        ('Trousers', 'Trousers'),
        ('Jackets', 'Jackets'),
        ('Coats', 'Coats'),
        ('Jeans', 'Jeans'),
        ('Underwears', 'Underwears')
    )

    name = models.CharField(max_length=50, unique=True)
    type = models.CharField(max_length=10, choices=TYPE_CHOICES)
    sub_type = models.CharField(max_length=20, choices=SUBTYPE_CHOICES, blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0)])
    img = models.ImageField(upload_to='apparels/img', height_field=None, width_field=None, max_length=None, null=True, blank=True)

    def __str__(self):
        return f"{self.name} - {self.get_type_display()} - {self.sub_type} - {self.price}"

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.CharField(max_length=100)
    pnumber = models.CharField(max_length=13)
    profilepic = models.ImageField(upload_to='profile/', height_field=None, width_field=None, max_length=None, null=True)

    def __str__(self) -> str:
        return f'user: {self.user}'
    
class CartItem(models.Model):
    cart_owner = models.ForeignKey(UserInfo, on_delete=models.CASCADE, related_name = 'cartitem')
    product_purchase = models.ForeignKey(Apparel, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    size = models.CharField(max_length =10)
    total_amount = models.DecimalField(max_digits=7, decimal_places=2)

    def update_total_amount(self):
        self.total_amount = self.quantity * self.product_purchase.price
        self.save()

    def __str__(self) -> str:
        return f'owner: {self.cart_owner} - {self.product_purchase}'
    
class OrderHistoryList(models.Model):
    owner =  models.ForeignKey(UserInfo, on_delete=models.CASCADE, related_name = 'history')
    itempurchased = models.ForeignKey(CartItem, on_delete=models.CASCADE)
    
    def transferitem(self):
        allitems = CartItem.objects.all()
        
        allitems.delete()
def truncate_apparel():
    with connection.cursor() as cursor:
        table_name = Apparel._meta.db_table
        cursor.execute(f'DELETE FROM {table_name};')
        cursor.execute(f'VACUUM;')

def truncate_cart():
    with connection.cursor() as cursor:
        table_name = CartItem._meta.db_table
        cursor.execute(f'DELETE FROM {table_name};')
        cursor.execute(f'VACUUM;')

apparelapp/views.py
from django.forms.models import BaseModelForm
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect

from django.views.generic import (TemplateView,
                                  ListView, DetailView,
                                  FormView, UpdateView, DeleteView )

from django.contrib.auth.mixins import LoginRequiredMixin #for CBV
from django.shortcuts import get_object_or_404
from .extras import send_email

from django.contrib.auth.models import Group, User

from .models import Apparel, CartItem, UserInfo, OrderHistoryList
from .forms import (ContactForm,
                    BotwearForm,TopwearForm,FootwearForm,
                    TopUpdateForm, BotUpdateForm, FootUpdateForm,
                    NewUserForm)

from decimal import Decimal

def redirecthome(request):
    return redirect('apparelapp:home')

#class views for template only
class HomeView(TemplateView):
    template_name = "apparelapp/index.html"

class ApparelsView(TemplateView):
    template_name = "apparelapp/apparels.html"

#classview that display the model
class BottomwearListView(ListView):
    model = Apparel
    template_name = "apparelapp/bottomwear_list.html"
    context_object_name = 'apparels'
    
    #to filter by type, in this case it will only select all bottomwears
    def get_queryset(self):
        queryset = super().get_queryset().filter(type='Bottomwear')
        sortbased = self.request.GET.get('radiofilter')

        #radio form that pass the value then sort by using order_by
        if sortbased == 'htol':
            queryset = queryset.order_by('-price')
        elif sortbased == 'ltoh':
            queryset = queryset.order_by('price')
        else:
            queryset = queryset
        return queryset

class TopwearListView(ListView):
    model = Apparel
    template_name = "apparelapp/topwear_list.html"
    context_object_name = 'apparels'

    def get_queryset(self):
        queryset = super().get_queryset().filter(type='Topwear')
        sortbased = self.request.GET.get('radiofilter')

        if sortbased == 'htol':
            queryset = queryset.order_by('-price')
        elif sortbased == 'ltoh':
            queryset = queryset.order_by('price')
        else:
            queryset = queryset
        return queryset

class FootwearListView(ListView):
    model = Apparel
    template_name = "apparelapp/footwear_list.html"
    context_object_name = 'apparels'

    def get_queryset(self):
        queryset = super().get_queryset().filter(type='Footwear')
        sortbased = self.request.GET.get('radiofilter')

        if sortbased == 'htol':
            queryset = queryset.order_by('-price')
        elif sortbased == 'ltoh':
            queryset = queryset.order_by('price')
        else:
            queryset = queryset
        return queryset

#used mixin enable for the user to login first to view this view
#detail view passes 1 object
class ApparelDetailView(LoginRequiredMixin, DetailView):
    model = Apparel
    context_object_name = 'apparel_details'
    template_name = "apparelapp/apparel_detail.html"

    # add another data which is form base on the subtype
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        item = self.get_object()
        if item.sub_type.strip() in ['Jeans','Trousers','Shorts','Underwears']:
            context["cart_form"] = BotwearForm()
        elif item.sub_type.strip() in ['Shirts','Coats','Jackets']:
            context['cart_form'] = TopwearForm()
        elif item.sub_type.strip() in ['Shoes']:
            context['cart_form'] = FootwearForm()
        return context
    
    #pass the answer base on subtype
    def post(self, request, *args, **kwargs):
        #get object get the currect objet selected
        apparel = self.get_object()
      
        if apparel.sub_type.strip() in ['Jeans','Trousers','Shorts','Underwears']:
            form = BotwearForm(request.POST)
        elif apparel.sub_type.strip() in ['Shirts','Coats','Jackets']:
            form = TopwearForm(request.POST)
        elif apparel.sub_type.strip() in ['Shoes']:
            form = FootwearForm(request.POST)
        buyer = UserInfo.objects.get(user=self.request.user)
       
       #if valid, check if the purchase and size were same, if not add another object, else, update
        if form.is_valid(): 
            qty = form.cleaned_data['quantity']
            total_price = Decimal(apparel.price) * Decimal(qty)
            sz = form.cleaned_data['size'].strip()

            cart_item = CartItem.objects.filter(product_purchase=apparel, size=sz).first()

            if cart_item:
                cart_item.quantity += int(qty)
                cart_item.total_amount += Decimal(total_price)
                cart_item.save()
            else:
                CartItem.objects.create(cart_owner=buyer,product_purchase=apparel,quantity=qty,size=sz,total_amount=float(total_price))
            return redirect('apparelapp:cart')
        else:
            context = self.get_context_data()
            context['cart_form'] = form
            return self.render_to_response(context)

class CartListView(LoginRequiredMixin, ListView):
    model = CartItem
    template_name = "apparelapp/cart_list.html"
    context_object_name = 'items'

    def get_queryset(self):
        return CartItem.objects.filter(cart_owner__user=self.request.user)
    
    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)
        total_eachitems = self.get_queryset()
        total = Decimal(sum([Decimal(item.total_amount) for item in total_eachitems]))
        numofitem = len([x for x in total_eachitems])
        context["total"] = total
        context['numofitems'] = numofitem
        return context
    

class CartUpdateView(LoginRequiredMixin, UpdateView):
    model = CartItem
    template_name = "apparelapp/cart_update.html"
    context_object_name = 'items'

    success_url = reverse_lazy('apparelapp:cart')

#overwrite the form_class
    def get_form_class(self) -> type[BaseModelForm]:
        item = self.object
        if item.product_purchase.sub_type.strip() in ['Jeans','Trousers','Shorts','Underwears']:
            return BotUpdateForm
        elif item.product_purchase.sub_type.strip() in ['Shirts','Coats','Jackets']:
            return TopUpdateForm
        elif item.product_purchase.sub_type.strip() in ['Shoes']:
            return FootUpdateForm
        return super().get_form_class()
    
    #call the form_class then add a name as updateform fopr templating
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['updateform'] = self.get_form()
        return context   

    def form_valid(self, form):
        #get the object
        cartitem = self.get_object()

        # to check if the qrty is zero, if yes, delete
        if cartitem.quantity <= 0:
            # CartItem.objects.filter(product_purchase=cartitem.product_purchase).delete() #or use this
            cartitem.delete()
            return HttpResponseRedirect(self.success_url)
        #to update the totalvalue of the item by calling the4 function
        cartitem.update_total_amount()
        return super().form_valid(form)
    
#use for direct delete in model
class CartDeleteView(LoginRequiredMixin, DeleteView):
    model = CartItem
    template_name = "apparelapp/cart_delete.html"
    context_object_name = 'items'

    success_url = reverse_lazy('apparelapp:cart')

class OrderHistoryListView(ListView):
    model = OrderHistoryList
    template_name = "apparelapp/orderhistory.html"
    context_object_name = 'itemhistory'

    def get_queryset(self):
        return OrderHistoryList.objects.filter(owner__user=self.request.user)

class CheckOutView(ListView):
    model = CartItem
    template_name = 'apparelapp/checkout.html'
    context_object_name = 'itemcheckout'

    def get_queryset(self):
        return CartItem.objects.filter(owner__user=self.request.user)
    


class UserInfoDetailView(LoginRequiredMixin, DetailView):
    model = UserInfo
    template_name = "apparelapp/account_detail.html"
    context_object_name = 'userinfo'

    def get_object(self, queryset=None):
        user_info = get_object_or_404(UserInfo, user=self.request.user)
        return user_info
    
class CreateUser(FormView):
    form_class = NewUserForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')

    def checkuserexists(self, username) -> bool:
        if User.objects.filter(username=username).exists():
            return True
        else:
            return False

    def form_valid(self, form):
        username = form.cleaned_data['username'].strip()

        if self.checkuserexists(username=username):
            form.add_error('username', 'This username is already taken. Please choose a different one.')
            return self.form_invalid(form)
        else:
            #assign each key to variable
            password = form.cleaned_data['password']
            firstname = form.cleaned_data['first_name']
            lastname = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            loc = form.cleaned_data['location']
            pnum = form.cleaned_data['pnumber']
            profpic = form.cleaned_data['profile']

            #creating user
            user = User.objects.create_user(username=username, email=email, password=password)
            user.first_name = firstname
            user.last_name = lastname

            #adding user to the group
            group = Group.objects.get(name='customers')
            user.groups.add(group)
            user.save()
            
            #create user's info
            UserInfo.objects.create(user=user, location=loc, pnumber=pnum, profilepic=profpic)
            return super().form_valid(form)
    

apparelapp/templates/apparelapp/cart_list.html
{% extends "base.html" %}

{% block title %}
My Cart
{% endblock title %}

{% block content %}

<div class='container' style='position:relative'>
    <div class='d-flex mt-2 justify-content-between' >
        <div class='d-flex mt-2'>
        <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-cart-dash" viewBox="0 0 16 16">
            <path d="M6.5 7a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1z"/>
            <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zm3.915 10L3.102 4h10.796l-1.313 7zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/>
        </svg>
        <h1 class='ms-5 me-3'>Your Shopping Cart</h1> <span class='m-auto fw-semibold'>{{numofitems}} item(s)</span>
        </div>
        <nav class="navbar">
            <div class="container-fluid">
              <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header">
                  <h5 class="offcanvas-title" id="offcanvasNavbarLabel">OPTION</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                  <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    <li class="nav-item my-2">
                        <a class='nav-link options' href="{% url "apparelapp:apparels" %}">
                            <div class='d-flex'>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
                                    </svg>
                                
                                <div class='px-3'>
                                    <h5 class='uline'>Back to Shop</h5>
                                </div>
                            </div>
                        </a>
                    </li>
                   <li class="nav-item my-2">
                    <a class='nav-link options' href="{% url "apparelapp:history" %}">
                        <div class='d-flex'>
                                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-folder-x" viewBox="0 0 16 16">
                                    <path d="M.54 3.87.5 3a2 2 0 0 1 2-2h3.672a2 2 0 0 1 1.414.586l.828.828A2 2 0 0 0 9.828 3h3.982a2 2 0 0 1 1.992 2.181L15.546 8H14.54l.265-2.91A1 1 0 0 0 13.81 4H2.19a1 1 0 0 0-.996 1.09l.637 7a1 1 0 0 0 .995.91H9v1H2.826a2 2 0 0 1-1.991-1.819l-.637-7a2 2 0 0 1 .342-1.31zm6.339-1.577A1 1 0 0 0 6.172 2H2.5a1 1 0 0 0-1 .981l.006.139q.323-.119.684-.12h5.396z"/>
                                    <path d="M11.854 10.146a.5.5 0 0 0-.707.708L12.293 12l-1.146 1.146a.5.5 0 0 0 .707.708L13 12.707l1.146 1.147a.5.5 0 0 0 .708-.708L13.707 12l1.147-1.146a.5.5 0 0 0-.707-.708L13 11.293z"/>
                                </svg>
                                <div class='px-3'>
                                    <h5 class='uline'>Order History</h5>
                                </div>
                            </div>
                        </a>
                    </li> 
                    <li class="nav-item dropdown my-2">
                        <div class='d-flex'>
                            <div>
                                <div>
                                    <button class="navbar-toggler justify-content-center" type='button' data-bs-toggle="collapse" data-bs-target="#summarycontent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-card-checklist text-primary" viewBox="0 0 16 16">
                                        <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2z"/>
                                        <path d="M7 5.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 1 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0M7 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 0 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0"/>
                                      </svg>
                                        Show Summary
                                    </button>
                                </div>                                
                                <div class="collapse" id="summarycontent" data-bs-theme="dark">
                                    <div class="p-4">
                                      <h3 style='color:black'>Summary</h3>
                                        <div>
                                            <h6>Order Total: ------------- {{total}} <h5>
                                            <h6>Shipping Fee: ------------ &#8369;30.00<h5>
                                            <hr>
                                            {% if numofitems == 0 %}
                                            <h5>Total: &#8369; {{total| add:0.00 }}<h5>
                                            {% else %}
                                            <h5>Total: &#8369; {{total| add:30.00 }}<h5>
                                            {% endif %} 
                                        </div>
                                    </div>
                                </div>                                  
                            </div>
                        </div>
                    </li>
                    <li class="nav-item  my-2">
                        <a class='nav-link options' href="{% url "apparelapp:apparels" %}">
                        <div class='d-flex'>
                                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-bag-check" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M10.854 8.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L7.5 10.793l2.646-2.647a.5.5 0 0 1 .708 0"/>
                                    <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1m3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1z"/>
                                </svg>
                                <div class='px-3'>
                                    <h5  class='uline'>Checkout</h5>
                                </div>
                            </div>
                        </a>
                    </li>
            
                  </ul>
                </div>
              </div>
            </div>
          </nav>
    </div>

    <div class='my-5'>
        {% for item in items %}
        <div class='d-flex align-items-center mb-2 bg-secondary rounded justify-content-between' style="background-image: url('{{item.product_purchase.img.url}}'); background-size:cover; background-position:center; box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);">
            <div class='col-10 d-flex p-3 align-items-center'>
                <div class='col-2'>
                    <img class='mx-3' src="{{item.product_purchase.img.url}}" alt='...' width="170" height="170" style='border-radius:50%;  box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);'>
                </div>
                <div class='col-910 d-flex justify-content-evenly'>
                    <h6 class='whiteblur mx-5'>{{item.product_purchase.name}}</h6>
                    <p class='whiteblur mx-5'>{{item.quantity}} pc(s)</p>
                    <p class='whiteblur mx-5'>{{item.size}}</p>
                    <p class='whiteblur'>{{item.total_amount}}</p>
                </div>
            </div>
            <div class='col-2 d-flex gap-5'>
                <div class='modifybutton mx-1'>
                    <a class='nav-link buttonblur' href="{% url "apparelapp:update" pk=item.id %}" style='color:orange' >
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325"/>
                      </svg>
                    </a>
                </div>
                <div class='modifybutton mx-5'>
                    <a class='nav-link buttonblur' href="{% url "apparelapp:delete" pk=item.id %}"  style='color:red' >
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                            <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock content %}

apparelapp/templates/apparelapp/checkout.html
{% extends "base.html" %}

{% block title %}Checkout{% endblock title %}

{% block content %}

{% endblock content %}

apparelapp/templates/apparelapp/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}HOME{% endblock title %}
{% block content %}
<section>
    <div class='header'>
        <div class="start-text">
            <p><i> &#8212; S T Y L I S H &#8212;</i></p>
            <h1>Men Clothes</h1>
            <p>100% off Summer Vacation</p>
            <a class='button' href="{% url "apparelapp:apparels" %}">SHOP NOW</a>
        </div>
    </div>
    <div id='service'>
        <div class="container">
            <div class="item">
                <img src="{% static "apparelapp/images/uidesign/freeshipping.jpg" %}" alt="...">
                <h3 class='title'>Free Shipping</h3>
                <p class='title-quote'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat, obcaecati!</p>
            </div>
            <div class="item">
                <img src="{% static "apparelapp/images/uidesign/247.png" %}" alt="...">
                <h3>Support 24/7</h3>
                <p class='title-quote'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat, obcaecati!</p>
            </div>
            <div class="item">
                <img src="{% static "apparelapp/images/uidesign/moneyback.png" %}" alt="...">
                <h3>Money Return</h3>
                <p class='title-quote'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat, obcaecati!</p>
            </div>
        </div>
    </div>
    <div class='category'>
        <div class='category-title'>
            <h3 class='title'> &#8212; Style Gallery &#8212; </h3>
            <p class='title-quote'>Swagger Up with Style Gallery's Dapper Picks for Men</p>
        </div>
        <div class='Gallery'>
            {% for i in "12345"|slice:":5" %}
            <div class="outfits">
                <img src="{% static "apparelapp/images/uidesign/outfit" %}{{forloop.counter}}.png" alt="outfit{{forloop.counter}}">
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<footer>
    <div class="row text-center">
        <div class="col-5">
            <h1>Men Apparel</h1>
            <p class='title-quote'> &#169; All Rights Reserved</p>
        </div>
        <div class="foot col">
            <div class="row">
                <div class='col'>
                    <h5>ABOUT US</h5>
                    <p>About us</p>
                    <p>Contact</p>
                    <p>Order tracking</p>
                </div>
                <div class='col'>
                    <h5>FOLLOW US</h5>
                    <p>Facebook</p>
                    <p>Twitter</p>
                    <p>Instagram</p>
                    <p>Youtube</p>
                </div>
            </div>
        </div>
        
    </div>
</footer>
{% endblock content %}