MenApparel/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('apparels/', include('apparelapp.urls')),
    path('', RedirectView.as_view(url='apparels/')),
    path('accounts/', include('django.contrib.auth.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apparelapp/urls.py
from django.urls import path
from .views import (HomeView, ApparelsView,
                    TopwearListView, BottomwearListView, FootwearListView,
                    ApparelDetailView, CartListView, CartDeleteView, CartUpdateView,
                    ContactFormView, UserInfoDetailView, CreateUser, OrderHistoryListView,
                    thankyoupage, redirecthome)

app_name = 'apparelapp'

urlpatterns = [
    path('', redirecthome, name='redirecthome'),
    path('home/', HomeView.as_view(), name='home'),

    path('catalog/', ApparelsView.as_view(), name='apparels'),
    path('catalog/topwears', TopwearListView.as_view(), name='topapparels'),
    path('catalog/bottomwears', BottomwearListView.as_view(), name='botapparels'),
    path('catalog/footwears', FootwearListView.as_view(), name='footapparels'),

    path('Addcart/<int:pk>/', ApparelDetailView.as_view(), name='addcart'),
    path('delete/<int:pk>/', CartDeleteView.as_view(), name='delete'),
    path('update/<int:pk>/', CartUpdateView.as_view(), name='update'),
    path('cart/', CartListView.as_view(), name='cart'),

    path('/history', OrderHistoryListView.as_view(), name='history'),
    # path(),

    path('account/', UserInfoDetailView.as_view(), name='account'),
    path('register/', CreateUser.as_view(), name='register'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('thankyou/', thankyoupage, name='thankyou')
]

templates/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}default title{% endblock title %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
        {% load static %}
        <link rel="stylesheet" href="{% static "apparelapp/css/style.css" %}">
        {% block extracss %}
        {% endblock extracss %}
    </head>
    <body style='{% block bodyStyle %}{% endblock bodyStyle %}'>
        <nav class="navbar navbar-expand-lg" style='background-color: #ffffff'>
            <div class="container-fluid">
              <a class="navbar-brand" href="#"><strong>Men Apparel</strong></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url "apparelapp:home" %}"> HOME </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url "apparelapp:cart" %}"> CART </a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                       SHOP 
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url "apparelapp:topapparels" %}">Topwears</a></li>
                      <li><a class="dropdown-item" href="{% url "apparelapp:botapparels" %}">Bottomwears</a></li>
                      <li><a class="dropdown-item" href="{% url "apparelapp:footapparels" %}">Footwear</a></li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url "apparelapp:contact" %}"> CONTACT </a>
                  </li>
                  {% if user.is_authenticated %}
                  

                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'apparelapp:account' %}">ACCOUNT</a>
                      {% comment %} maybe try disbling it {% endcomment %}
                  </li>
                  <li class="nav-item">
                    <a class='nav-link' href="{% url "logout"%}">logout</a>
                  </li>
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">LOGIN</a>
                  </li>
                  {% endif %}
                  
                </ul>
              </div>
            </div>
          </nav>
        {% block content %}
        default content
        {% endblock content %}
    </body>
</html>